baseURL = "https://tapaskapadia.github.io/sec-word-clouds"
languageCode = "en-us"
title = "SEC Form Visualizations"
theme = "newsroom"
[taxonomies]
  companies = "companies"
  industry = "industry"
  tag = "tags"
  form = "forms"
[params]
  disableDarkMode = true 
[author]
    name = "Tapas"
    homepage = "https://github.com/tapaskapadia"

