name: pipeline testing

on:
  push:
    branches:
      - pipelineTesting  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: main
      - name: Checkout python script repo
        uses: actions/checkout@v2
        with:
          repository: tapaskapadia/sec-forms-word-cloud-script
          path: generate
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check files
        run: |
          ls -la 
          pwd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r generate/requirements.txt
        working-directory: ./generate